# Mongo
#mongo.uri=mongodb://localhost:27017
mongo.uri=mongodb://admin:admin123@localhost:27017/?authSource=admin
mongo.database=company_db
mongo.collection=employees_encrypted

# Files
employees.csv.path=Company-Employee.Database/Dataset-Emp-Database.csv

# Key storage
keys.directory=client/index
